local M = {}

---@param conf VagueColorscheme.InternalConfig
M.get_colors = function(conf)
  local c = conf.colors

  -- stylua: ignore
  ---@type table<string, vim.api.keyset.highlight>
  local hl = {
    ColorColumn      = { bg = c.line },
    Conceal          = { fg = c.func, bg = c.bg },
    CurSearch        = { fg = c.fg, bg = c.search or c.visual },
    Cursor           = { reverse = true },
    vCursor          = { reverse = true },
    iCursor          = { reverse = true },
    lCursor          = { reverse = true },
    CursorIM         = { reverse = true },
    CursorColumn     = { bg = c.line },
    CursorLine       = { bg = c.line },
    CursorLineNr     = { fg = c.fg },
    Debug            = { fg = c.constant },
    debugPC          = { fg = c.bg, bg = c.fg },
    debugBreakpoint  = { fg = c.bg, bg = c.operator },
    Directory        = { fg = c.hint },
    ErrorMsg         = { fg = c.error, bold = true },
    EndOfBuffer      = { fg = c.comment or c.bg },
    FloatBorder      = { fg = c.floatBorder, bg = conf.transparent and "none" or c.bg },
    FloatTitle       = { fg = c.floatBorder, bg = conf.transparent and "none" or c.bg },
    FloatFooter      = { fg = c.floatBorder, bg = conf.transparent and "none" or c.bg },
    Folded           = { fg = c.comment, bg = conf.transparent and "none" or c.line },
    FoldColumn       = { fg = c.comment, bg = conf.transparent and "none" or c.bg },
    IncSearch        = { fg = c.bg, bg = c.search or c.visual },
    LineNr           = { fg = c.comment },
    MatchParen       = { fg = c.fg, bg = c.visual },
    MoreMsg          = { fg = c.func, bold = true },
    MsgSeparator     = { fg = c.string, bg = c.line, bold = true },
    NonText          = { fg = c.comment },
    Normal           = { fg = c.fg, bg = conf.transparent and "none" or c.bg },
    NormalFloat      = { fg = c.fg, bg = conf.transparent and "none" or c.bg },
    ModeMsg          = { fg = c.string },
    Pmenu            = { fg = c.fg, bg = c.bg },
    PmenuSel         = { fg = c.constant, bg = c.line },
    PmenuSbar        = { fg = c.visual, bg = c.comment },
    PmenuThumb       = { fg = c.comment, bg = c.visual },
    Question         = { fg = c.constant },
    QuickFixLine     = { fg = c.func, underline = true },
    Search           = { fg = c.fg, bg = c.search or c.visual },
    SignColumn       = { fg = c.fg, bg = conf.transparent and "none" or c.bg },
    SpecialKey       = { fg = c.comment },
    SpellBad         = { fg = "none", undercurl = true },
    SpellCap         = { fg = "none", undercurl = true },
    SpellLocal       = { fg = "none", undercurl = true },
    SpellRare        = { fg = "none", undercurl = true },
    StatusLine       = { fg = c.fg, bg = c.comment },
    StatusLineTerm   = { fg = c.fg, bg = c.line },
    StatusLineNC     = { fg = c.comment, bg = c.bg },
    StatusLineTermNC = { fg = c.comment, bg = c.line },
    Substitute       = { fg = c.type, bg = c.visual },
    TabLine          = { fg = c.fg, bg = c.line },
    TabLineFill      = { fg = c.comment, bg = c.line },
    TabLineSel       = { fg = c.bg, bg = c.fg },
    Terminal         = { fg = c.fg, bg = conf.transparent and "none" or c.bg },
    ToolbarButton    = { fg = c.bg, bg = c.visual },
    ToolbarLine      = { fg = c.fg },
    Visual           = { fg = c.fg, bg = c.visual },
    VisualNOS        = { fg = "none", bg = c.comment, underline = true },
    WarningMsg       = { fg = c.warning, bold = true },
    Whitespace       = { fg = c.comment },
    WildMenu         = { fg = c.bg, bg = c.func },
    WinSeparator     = { fg = c.floatBorder },
  }

  return hl
end
return M
